### ISSUE TITLE
self.count and self.running_loss in models/model_s2c.py

### ISSUE THREAD

**Issue by jennytenghere** [sangrockEG/S2C#6]
I think there is something missing in the model_s2c.py file.
Unlike model_vanilla.py, model_s2c.py doesn't have the # Visualize block.
So self.count will equal to zero in the whole process and cause the ZeroDivisionError in print_log() function.
And the losses shown in the terminal will be all zero.
I'm not sure if I am right.
Thank you.

**Comment by Weiw1819** [comment]
Traceback (most recent call last):
  File "train.py", line 152, in <module>
    model.print_log(epo + 1, count, writer)
  File "/home/wc/projects/S2C/models/model_s2c.py", line 431, in print_log
    loss_str += self.loss_names[i] + ' : ' + str(round(self.running_loss[i] / self.count, 5)) + ', '
ZeroDivisionError: division by zero

**Comment by Weiw1819** [comment]
Can the author answer this question？

**Comment by Dawood-Amir** [comment]
> Can the author answer this question？

Hi, I have run into the same issue, did you happen to find any solution?

Thanks

**Comment by jennytenghere** [comment]
I still can't find the solution.
Since I don't know how many lines of code are missing, I gave up training this model.
